Improve test coverage
KSDaemon/wampy.js pull request #249
Opened 2023-01-14 22:50 UTC by lucasrmendonca

### Description, Motivation and Context
- Remove/comment out unreachable branches from wampy.js
- Reach 100% test coverage in utils.js by converting getWebsocket params into an options Object that allows for a browser mock flag.

### What kind of change does this PR introduce?
- [x] Refactoring (no new functionality, only code improvements)

### Checklist:
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] Overall test coverage is not decreased.
- [x] All new and existing tests passed.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-01-15 02:01 UTC, lucasrmendonca commented
Although code climate is complaining, this change fixed 4 code climate issues while introducing 1 new one, so it's still an improvement

2023-01-16 21:43 UTC, KSDaemon requested changes

2023-01-16 21:43 UTC, KSDaemon commented on src/utils.js
> +export function getWebSocket (wampy = {}) {
As it is not clear from the function definition what options it uses, I think we need at least to describe it in @JSDoc format: prop + format + optional? + desc
example: 
```js
/**
  * @param {Object} userInfo Information about the user.
  * @param {string} userInfo.name The name of the user.
  * @param {string} userInfo.email The email of the user.
  */
 function logIn(userInfo) {
        doLogIn(userInfo.name, userInfo.email);
 }
```

2023-01-17 00:59 UTC, lucasrmendonca commented
I've added the jsdoc comment block and also fixed codeclimate's complaint by creating a helper function just for the case when the WebSocket class is part of the global `window` object, let me know if this is ok

2023-01-17 07:40 UTC, KSDaemon commented
Okay. Let's land this. 👍🏻

2023-01-17 07:40 UTC, merged